name: main
on:
  workflow_dispatch:
  push:
    paths:
      - "AKSWebApp/**"
jobs:
  ACRBuild:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.SERVICE_PRINCIPAL }}
          service_principal_password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          tenant: ${{ secrets.TENANT }}
          registry: ${{ secrets.REGISTRY }}
          repository: ${{ secrets.REPOSITORY }}
          image: akswebapp
          folder: AKSWebApp
          branch: main
  Update-K8s-Manifests:
    name: Update K8s Deployment Manifest with Image Version
    needs: ACRBuild
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Update image name in manifest file
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-ChildItem
          Write-Output "----"
          Get-ChildItem -Path $GITHUB_WORKSPACE/work
          $line = Get-Content $GITHUB_WORKSPACE/work/AKSWebApp/Manifests/deployment.yaml | Select-String image: | Select-Object -ExpandProperty Line
          $content = Get-Content $GITHUB_WORKSPACE/work/AKSWebApp/Manifests/deployment.yaml
          $content | ForEach-Object {$_ -replace $line,"        image: ${{ secrets.REGISTRY }}.azurecr.io/${{ secrets.REPOSITORY }}:${{ github.run_number }}"} | Set-Content $GITHUB_WORKSPACE/work/AKSWebApp/Manifests/deployment.yaml
        azPSVersion: "latest"
    
    - name: Commit changes in manifest to repo
      run: | 
        git config user.name "GitHub Actions Bot"
        git config user.email ""
        git add Manifests/deployment.yaml
        git commit -m "Update image version in K8s Deployment manifests file"
        git push origin
